const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: '/images/item-1.jpeg',
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero, doloribus voluptas molestias natus ut cupiditate voluptatem maxime distinctio, minima cumque voluptatibus facere. Possimus, delectus quos?`,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: '/images/item-2.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa omnis quo ea quasi magnam cumque. `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: '/images/item-3.jpeg',
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Autem repudiandae incidunt minus.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: '/images/item-4.jpeg',
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic quidem quis. `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: '/images/item-5.jpeg',
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Adipisci `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: '/images/item-6.jpeg',
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore cum unde iste!`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: '/images/item-7.jpeg',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus, facilis minima qui at, in a ea modi illum. `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: '/images/item-8.jpeg',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium delectus nihil dignissimos ea molestias iste atque itaque molestiae?`,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: '/images/item-9.jpeg',
    desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magni, natus quisquam culpa nobis dolores nam alias.`,
  },
];
export default menu;
